return {
  { "echasnovski/mini.surround", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "gbprod/yanky.nvim", enabled = false },
  { "ggandor/flit.nvim", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  { "jbyuki/one-small-step-for-vimkind", enabled = false },
  { "linux-cultist/venv-selector.nvim", enabled = false },
  { "mfussenegger/nvim-dap", enabled = false },
  { "mfussenegger/nvim-dap-python", enabled = false },
  { "nvim-treesitter/nvim-treesitter-context", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "rcarriga/nvim-dap-ui", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
}
